### ISSUE TITLE
Detect disconnections

### ISSUE THREAD

**Issue by ghost** [evilive3000/poloniex-orderbook#18]
Hello, 

How can I detect a disconnection of the websocket?

Is it only a single websocket for all streams or multiple websockets?

Thanks

**Comment by evilive3000** [comment]
> How can I detect a disconnection of the websocket?

well, you can try to listen for event `close` on `poloman.socket` object:
`poloman.socket.on('close', () => {...})`, but it might not being fired on disconnects due to network failure (see [issue](https://github.com/websockets/ws/issues/686))

> Is it only a single websocket for all streams or multiple websockets?

The manager uses single ws connection for multiple orderbooks.
